export type DateFormat =
  'YYYYMMDD'
  | 'YYYY-MM-DD'
  | 'YYYY/MM/DD'
  | 'jYYYY/jMM/jDD'
  | 'jYYYY-jMM-jDD'
  | 'jYYYYjMMjDD'
  | 'timestamp'
  | 'jYYYY/jMM/jDD HH:mm'
  | 'jYYYY-jMM-jDD HH:mm'
  | 'jYYYYjMMjDD HH:mm'
  | 'YYYY/MM/DD HH:mm'
  | 'YYYY-MM-DD HH:mm'
  | 'YYYYMMDD HH:mm'
